import { ColorScheme } from "@/hooks/useTheme";
import { StyleSheet } from "react-native";

export const createHomeStyles = (colors: ColorScheme) => {
    const styles = StyleSheet.create({
        container: {
            flex: 1,
            backgroundColor: colors.bg,
        },
        safeArea: {
            flex: 1,
            backgroundColor: "transparent",
        },
        loadingContainer: {
            flex: 1,
            justifyContent: "center",
            alignItems: "center",
            backgroundColor: colors.bg,
        },
        loadingText: {
            marginTop: 20,
            fontSize: 16,
            fontWeight: "600",
            color: colors.text,
            letterSpacing: 0.3,
        },
        header: {
            paddingHorizontal: 24,
            paddingTop: 20,
            paddingBottom: 26,
            backgroundColor: "transparent",
        },
        titleContainer: {
            flexDirection: "row",
            alignItems: "center",
            marginBottom: 24,
        },
        iconContainer: {
            width: 60,
            height: 60,
            borderRadius: 20,
            justifyContent: "center",
            alignItems: "center",
            marginRight: 16,
            shadowColor: colors.shadow,
            shadowOffset: {
                width: 0,
                height: 3,
            },
            shadowOpacity: 0.12,
            shadowRadius: 6,
            elevation: 4,
        },
        titleTextContainer: {
            flex: 1,
        },
        title: {
            fontSize: 34,
            fontWeight: "800",
            letterSpacing: -0.5,
            marginBottom: 6,
            color: colors.text,
        },
        subtitle: {
            fontSize: 15,
            fontWeight: "500",
            color: colors.textMuted,
            letterSpacing: 0.2,
        },
        progressContainer: {
            marginTop: 10,
        },
        progressBarContainer: {
            flexDirection: "row",
            alignItems: "center",
            gap: 14,
        },
        progressBar: {
            flex: 1,
            height: 14,
            borderRadius: 8,
            overflow: "hidden",
            backgroundColor: colors.border,
            shadowColor: colors.shadow,
            shadowOffset: {
                width: 0,
                height: 2,
            },
            shadowOpacity: 0.08,
            shadowRadius: 4,
            elevation: 2,
        },
        progressFill: {
            height: "100%",
            borderRadius: 8,
        },
        progressText: {
            fontSize: 14,
            fontWeight: "700",
            minWidth: 46,
            textAlign: "right",
            color: colors.success,
            letterSpacing: 0.3,
        },
        mainPanel: {
            flex: 1,
            marginHorizontal: 12,
            borderTopLeftRadius: 32,
            borderTopRightRadius: 32,
            backgroundColor: colors.bg,
            borderWidth: 1,
            borderColor: colors.border,
            overflow: "hidden",
            shadowColor: colors.shadow,
            shadowOffset: {
                width: 0,
                height: -4,
            },
            shadowOpacity: 0.16,
            shadowRadius: 12,
            elevation: 10,
        },
        inputSection: {
            paddingHorizontal: 22,
            paddingTop: 22,
            paddingBottom: 16,
            backgroundColor: "transparent",
        },
        inputWrapper: {
            flexDirection: "row",
            alignItems: "center",
            gap: 12,
        },
        input: {
            flex: 1,
            borderWidth: 2,
            borderRadius: 18,
            paddingHorizontal: 20,
            paddingVertical: 16,
            fontSize: 16,
            maxHeight: 120,
            fontWeight: "500",
            backgroundColor: colors.backgrounds.input,
            borderColor: colors.border,
            color: colors.text,
            shadowColor: colors.shadow,
            shadowOffset: {
                width: 0,
                height: 2,
            },
            shadowOpacity: 0.06,
            shadowRadius: 4,
            elevation: 2,
        },
        inputFocused: {
            borderColor: colors.primary,
            borderWidth: 2,
        },
        addButton: {
            width: 54,
            height: 54,
            borderRadius: 27,
            justifyContent: "center",
            alignItems: "center",
            shadowColor: colors.shadow,
            shadowOffset: {
                width: 0,
                height: 4,
            },
            shadowOpacity: 0.2,
            shadowRadius: 8,
            elevation: 5,
        },
        addButtonDisabled: {
            opacity: 0.6,
        },
        todoList: {
            flex: 1,
            backgroundColor: "transparent",
        },
        todoListContent: {
            paddingHorizontal: 22,
            paddingTop: 10,
            paddingBottom: 150,
        },
        emptyListContainer: {
            flexGrow: 1,
            justifyContent: "center",
            backgroundColor: colors.bg,
        },
        todoItemWrapper: {
            marginVertical: 9,
        },
        todoItem: {
            flexDirection: "row",
            alignItems: "flex-start",
            padding: 18,
            borderRadius: 18,
            borderWidth: 1,
            borderColor: colors.border,
            shadowColor: colors.shadow,
            shadowOffset: {
                width: 0,
                height: 3,
            },
            shadowOpacity: 0.16,
            shadowRadius: 8,
            elevation: 6,
        },
        checkbox: {
            marginRight: 16,
            marginTop: 2,
        },
        checkboxInner: {
            width: 32,
            height: 32,
            borderRadius: 10,
            borderWidth: 2,
            justifyContent: "center",
            alignItems: "center",
        },
        todoTextContainer: {
            flex: 1,
        },
        todoText: {
            fontSize: 17,
            lineHeight: 24,
            fontWeight: "500",
            marginBottom: 14,
            color: colors.text,
            letterSpacing: 0.2,
        },
        todoActions: {
            flexDirection: "row",
            gap: 12,
        },
        actionButton: {
            width: 40,
            height: 40,
            borderRadius: 10,
            justifyContent: "center",
            alignItems: "center",
        },
        editContainer: {
            flex: 1,
        },
        editInput: {
            borderWidth: 2,
            borderRadius: 14,
            paddingHorizontal: 16,
            paddingVertical: 12,
            fontSize: 16,
            fontWeight: "500",
            marginBottom: 16,
            backgroundColor: colors.backgrounds.editInput,
            borderColor: colors.primary,
            color: colors.text,
        },
        editButtons: {
            flexDirection: "row",
            gap: 10,
        },
        editButton: {
            flexDirection: "row",
            alignItems: "center",
            gap: 6,
            paddingHorizontal: 14,
            paddingVertical: 10,
            borderRadius: 10,
        },
        editButtonText: {
            color: "#ffffff",
            fontSize: 13,
            fontWeight: "600",
            letterSpacing: 0.3,
        },
        emptyContainer: {
            alignItems: "center",
            justifyContent: "center",
            paddingVertical: 84,
            backgroundColor: "transparent",
        },
        emptyIconContainer: {
            width: 132,
            height: 132,
            borderRadius: 66,
            justifyContent: "center",
            alignItems: "center",
            marginBottom: 28,
            shadowColor: colors.shadow,
            shadowOffset: {
                width: 0,
                height: 4,
            },
            shadowOpacity: 0.1,
            shadowRadius: 8,
            elevation: 4,
        },
        emptyText: {
            fontSize: 26,
            fontWeight: "800",
            marginBottom: 12,
            color: colors.text,
            letterSpacing: -0.3,
        },
        emptySubtext: {
            fontSize: 15,
            textAlign: "center",
            paddingHorizontal: 44,
            lineHeight: 24,
            color: colors.textMuted,
            letterSpacing: 0.2,
            fontWeight: "500",
        },
    });

    return styles;
};
