import { ColorScheme } from "@/hooks/useTheme";
import { StyleSheet } from "react-native";

export const createHomeStyles = (colors: ColorScheme) => {
    const styles = StyleSheet.create({
        container: {
            flex: 1,
            backgroundColor: colors.bg,
        },
        safeArea: {
            flex: 1,
            backgroundColor: "transparent",
        },
        loadingContainer: {
            flex: 1,
            justifyContent: "center",
            alignItems: "center",
            backgroundColor: colors.bg,
        },
        loadingText: {
            marginTop: 20,
            fontSize: 16,
            fontWeight: "600",
            color: colors.text,
            letterSpacing: 0.3,
        },
        header: {
            paddingHorizontal: 22,
            paddingTop: 14,
            paddingBottom: 20,
            backgroundColor: "transparent",
        },
        titleContainer: {
            flexDirection: "row",
            alignItems: "center",
            marginBottom: 18,
        },
        iconContainer: {
            width: 56,
            height: 56,
            borderRadius: 18,
            justifyContent: "center",
            alignItems: "center",
            marginRight: 14,
            shadowColor: colors.shadow,
            shadowOffset: {
                width: 0,
                height: 3,
            },
            shadowOpacity: 0.12,
            shadowRadius: 6,
            elevation: 4,
        },
        titleTextContainer: {
            flex: 1,
        },
        title: {
            fontSize: 32,
            fontWeight: "800",
            letterSpacing: -0.5,
            marginBottom: 4,
            color: colors.text,
        },
        subtitle: {
            fontSize: 14,
            fontWeight: "500",
            color: colors.textMuted,
            letterSpacing: 0.2,
        },
        progressContainer: {
            marginTop: 6,
        },
        progressBarContainer: {
            flexDirection: "row",
            alignItems: "center",
            gap: 14,
        },
        progressBar: {
            flex: 1,
            height: 12,
            borderRadius: 7,
            overflow: "hidden",
            backgroundColor: colors.border,
            shadowColor: colors.shadow,
            shadowOffset: {
                width: 0,
                height: 2,
            },
            shadowOpacity: 0.08,
            shadowRadius: 4,
            elevation: 2,
        },
        progressFill: {
            height: "100%",
            borderRadius: 7,
        },
        progressText: {
            fontSize: 13,
            fontWeight: "700",
            minWidth: 44,
            textAlign: "right",
            color: colors.success,
            letterSpacing: 0.3,
        },
        mainPanel: {
            flex: 1,
            marginHorizontal: 10,
            borderTopLeftRadius: 28,
            borderTopRightRadius: 28,
            backgroundColor: colors.surface,
            overflow: "hidden",
            shadowColor: colors.shadow,
            shadowOffset: {
                width: 0,
                height: -3,
            },
            shadowOpacity: 0.12,
            shadowRadius: 10,
            elevation: 8,
        },
        inputSection: {
            paddingHorizontal: 18,
            paddingTop: 18,
            paddingBottom: 10,
            backgroundColor: "transparent",
        },
        inputWrapper: {
            flexDirection: "row",
            alignItems: "center",
            gap: 12,
        },
        input: {
            flex: 1,
            borderWidth: 1.5,
            borderRadius: 16,
            paddingHorizontal: 18,
            paddingVertical: 14,
            fontSize: 16,
            maxHeight: 120,
            fontWeight: "500",
            backgroundColor: colors.backgrounds.input,
            borderColor: colors.border,
            color: colors.text,
            shadowColor: colors.shadow,
            shadowOffset: {
                width: 0,
                height: 2,
            },
            shadowOpacity: 0.06,
            shadowRadius: 4,
            elevation: 2,
        },
        inputFocused: {
            borderColor: colors.primary,
            borderWidth: 2,
        },
        addButton: {
            width: 50,
            height: 50,
            borderRadius: 25,
            justifyContent: "center",
            alignItems: "center",
            shadowColor: colors.shadow,
            shadowOffset: {
                width: 0,
                height: 4,
            },
            shadowOpacity: 0.2,
            shadowRadius: 8,
            elevation: 5,
        },
        addButtonDisabled: {
            opacity: 0.6,
        },
        todoList: {
            flex: 1,
            backgroundColor: "transparent",
        },
        todoListContent: {
            paddingHorizontal: 18,
            paddingTop: 8,
            paddingBottom: 130,
        },
        emptyListContainer: {
            flexGrow: 1,
            justifyContent: "center",
            backgroundColor: colors.bg,
        },
        todoItemWrapper: {
            marginVertical: 7,
        },
        todoItem: {
            flexDirection: "row",
            alignItems: "flex-start",
            padding: 16,
            borderRadius: 16,
            shadowColor: colors.shadow,
            shadowOffset: {
                width: 0,
                height: 3,
            },
            shadowOpacity: 0.12,
            shadowRadius: 6,
            elevation: 4,
        },
        checkbox: {
            marginRight: 14,
            marginTop: 1,
        },
        checkboxInner: {
            width: 30,
            height: 30,
            borderRadius: 9,
            borderWidth: 2,
            justifyContent: "center",
            alignItems: "center",
        },
        todoTextContainer: {
            flex: 1,
        },
        todoText: {
            fontSize: 16,
            lineHeight: 22,
            fontWeight: "500",
            marginBottom: 12,
            color: colors.text,
            letterSpacing: 0.2,
        },
        todoActions: {
            flexDirection: "row",
            gap: 10,
        },
        actionButton: {
            width: 38,
            height: 38,
            borderRadius: 9,
            justifyContent: "center",
            alignItems: "center",
        },
        editContainer: {
            flex: 1,
        },
        editInput: {
            borderWidth: 2,
            borderRadius: 14,
            paddingHorizontal: 16,
            paddingVertical: 12,
            fontSize: 16,
            fontWeight: "500",
            marginBottom: 16,
            backgroundColor: colors.backgrounds.editInput,
            borderColor: colors.primary,
            color: colors.text,
        },
        editButtons: {
            flexDirection: "row",
            gap: 10,
        },
        editButton: {
            flexDirection: "row",
            alignItems: "center",
            gap: 6,
            paddingHorizontal: 14,
            paddingVertical: 10,
            borderRadius: 10,
        },
        editButtonText: {
            color: "#ffffff",
            fontSize: 13,
            fontWeight: "600",
            letterSpacing: 0.3,
        },
        emptyContainer: {
            alignItems: "center",
            justifyContent: "center",
            paddingVertical: 64,
            backgroundColor: "transparent",
        },
        emptyIconContainer: {
            width: 120,
            height: 120,
            borderRadius: 60,
            justifyContent: "center",
            alignItems: "center",
            marginBottom: 22,
            shadowColor: colors.shadow,
            shadowOffset: {
                width: 0,
                height: 4,
            },
            shadowOpacity: 0.1,
            shadowRadius: 8,
            elevation: 4,
        },
        emptyText: {
            fontSize: 24,
            fontWeight: "800",
            marginBottom: 10,
            color: colors.text,
            letterSpacing: -0.3,
        },
        emptySubtext: {
            fontSize: 14,
            textAlign: "center",
            paddingHorizontal: 36,
            lineHeight: 22,
            color: colors.textMuted,
            letterSpacing: 0.2,
            fontWeight: "500",
        },
    });

    return styles;
};
