import { ColorScheme } from "@/hooks/useTheme";
import { StyleSheet } from "react-native";

export const createSettingsStyles = (colors: ColorScheme) => {
    const styles = StyleSheet.create({
        container: {
            flex: 1,
            backgroundColor: colors.bg,
        },
        safeArea: {
            flex: 1,
            backgroundColor: "transparent",
        },
        header: {
            paddingHorizontal: 24,
            paddingTop: 20,
            paddingBottom: 26,
            backgroundColor: "transparent",
        },
        titleContainer: {
            flexDirection: "row",
            alignItems: "center",
        },
        iconContainer: {
            width: 60,
            height: 60,
            borderRadius: 20,
            justifyContent: "center",
            alignItems: "center",
            marginRight: 16,
            shadowColor: colors.shadow,
            shadowOffset: {
                width: 0,
                height: 3,
            },
            shadowOpacity: 0.12,
            shadowRadius: 6,
            elevation: 4,
        },
        titleTextContainer: {
            flex: 1,
        },
        title: {
            fontSize: 34,
            fontWeight: "800",
            letterSpacing: -0.5,
            color: colors.text,
        },
        subtitle: {
            marginTop: 6,
            fontSize: 15,
            fontWeight: "500",
            color: colors.textMuted,
            letterSpacing: 0.2,
        },
        mainPanel: {
            flex: 1,
            marginHorizontal: 12,
            borderTopLeftRadius: 32,
            borderTopRightRadius: 32,
            backgroundColor: colors.bg,
            borderWidth: 1,
            borderColor: colors.border,
            overflow: "hidden",
            shadowColor: colors.shadow,
            shadowOffset: {
                width: 0,
                height: -4,
            },
            shadowOpacity: 0.16,
            shadowRadius: 12,
            elevation: 10,
        },
        scrollView: {
            flex: 1,
        },
        content: {
            paddingHorizontal: 22,
            paddingTop: 22,
            gap: 18,
            paddingBottom: 150,
        },
        section: {
            borderRadius: 18,
            padding: 22,
            backgroundColor: colors.surface,
            borderWidth: 1,
            borderColor: colors.border,
            shadowColor: colors.shadow,
            shadowOffset: {
                width: 0,
                height: 3,
            },
            shadowOpacity: 0.14,
            shadowRadius: 7,
            elevation: 5,
        },
        sectionTitle: {
            fontSize: 18,
            fontWeight: "800",
            marginBottom: 18,
            letterSpacing: -0.3,
            color: colors.text,
        },
        sectionTitleDanger: {
            fontSize: 18,
            fontWeight: "800",
            marginBottom: 18,
            letterSpacing: -0.3,
            color: colors.danger,
        },
        statsContainer: {
            gap: 14,
        },
        statCard: {
            flexDirection: "row",
            alignItems: "center",
            padding: 18,
            borderRadius: 14,
            borderLeftWidth: 4,
            backgroundColor: colors.bg,
            borderWidth: 1,
            borderColor: colors.border,
        },
        statIconContainer: {
            marginRight: 14,
        },
        statIcon: {
            width: 44,
            height: 44,
            borderRadius: 12,
            justifyContent: "center",
            alignItems: "center",
        },
        statNumber: {
            fontSize: 26,
            fontWeight: "800",
            letterSpacing: -0.5,
            color: colors.text,
        },
        statLabel: {
            fontSize: 13,
            fontWeight: "600",
            marginTop: 4,
            color: colors.textMuted,
            letterSpacing: 0.2,
        },
        settingItem: {
            flexDirection: "row",
            justifyContent: "space-between",
            alignItems: "center",
            paddingVertical: 18,
            borderBottomWidth: 1,
            borderBottomColor: colors.border,
        },
        settingLeft: {
            flexDirection: "row",
            alignItems: "center",
            flex: 1,
        },
        settingIcon: {
            width: 40,
            height: 40,
            borderRadius: 10,
            justifyContent: "center",
            alignItems: "center",
            marginRight: 14,
        },
        settingText: {
            fontSize: 16,
            fontWeight: "600",
            color: colors.text,
            letterSpacing: 0.2,
        },
        actionButton: {
            flexDirection: "row",
            alignItems: "center",
            justifyContent: "space-between",
            paddingVertical: 18,
            borderBottomWidth: 1,
            borderBottomColor: colors.border,
        },
        actionLeft: {
            flexDirection: "row",
            alignItems: "center",
            flex: 1,
        },
        actionIcon: {
            width: 40,
            height: 40,
            borderRadius: 10,
            justifyContent: "center",
            alignItems: "center",
            marginRight: 14,
        },
        actionText: {
            fontSize: 16,
            fontWeight: "600",
            color: colors.text,
            letterSpacing: 0.2,
        },
        actionTextDanger: {
            fontSize: 16,
            fontWeight: "600",
            color: colors.danger,
            letterSpacing: 0.2,
        },
    });

    return styles;
};
